name: CI/CD
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    branches: 
      - master
  
jobs:
  _run_tests_:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python 3.10.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry==1.3.2
          poetry install
      - name: Run linting with flake8
        run: poetry run flake8 .
      - name: Run typing with mypy
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest
      
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
      - run: echo "🍏 This job's status is ${{ job.status }}."

